// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Shooter.h"
#include "../RobotMap.h"
#include "../Robot.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Shooter::Shooter() : Subsystem("Shooter") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid1 = RobotMap::shooterSolenoid1;
    cANTalon1 = RobotMap::shooterCANTalon1;
    cANTalon1->Disable();
    cANTalon1->SetFeedbackDevice(CANTalon::QuadEncoder);
    cANTalon1->SetSensorDirection(true);
    cANTalon2 = RobotMap::shooterCANTalon2;
    cANTalon2->Disable();
    cANTalon2->SetFeedbackDevice(CANTalon::QuadEncoder);
    cANTalon2->SetSensorDirection(true);
    cANTalon3 = RobotMap::shooterCANTalon3;
    cANTalon3->Disable();
    cANTalon3->SetFeedbackDevice(CANTalon::AnalogEncoder);
    //cANTalon3->ConfigPotentiometerTurns(10);
    cANTalon4 = RobotMap::shooterCANTalon4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Shooter::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Shooter::Load() {
	cANTalon1->Enable();
	cANTalon1->SetSetpoint(7000);
	cANTalon2->Enable();
	cANTalon2->SetSetpoint(-7000);
}

void Shooter::SpinUpTheWheels() {
	cANTalon1->Enable();
	cANTalon1->SetSetpoint(-10000);
	cANTalon2->Enable();
	cANTalon2->SetSetpoint(-10000);
}

void Shooter::Fire() {
	Solenoid1->Set(true);
}

void Shooter::Stop() {
	cANTalon1->Disable();
	cANTalon2->Disable();
	cANTalon3->SetSetpoint(0);
	//cANTalon3->Disable();
	//cANTalon3->Set(0.0);
	Solenoid1->Set(false);
}

void Shooter::Angle() {
	cANTalon3->Enable();
	cANTalon3->SetSetpoint(512);
	//cANTalon3->Set(joystick);
}
