



#ifndef AUTOPOS1_H
#define AUTOPOS1_H

#include "Commands/CommandGroup.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutoPos1: public CommandGroup {
public:

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutoPos1();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

private:

};

#endif
