// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveRobot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveRobot::DriveRobot(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveRobot::Initialize() {
	Robot::chassis->Engage();
}

// Called repeatedly when this Command is scheduled to run
void DriveRobot::Execute() {
	if (Robot::oi->getjoy1()->GetRawButton(1) && Robot::oi->getjoy2()->GetRawButton(1)) {
		Robot::chassis->DriveHigh(Robot::oi->getjoy1(), Robot::oi->getjoy2());
	} else {
		Robot::chassis->Drive(Robot::oi->getjoy1(), Robot::oi->getjoy2());
	}
	SmartDashboard::PutNumber("Yaw", Robot::navX->ahrs->GetYaw());
	SmartDashboard::PutNumber("Pitch", Robot::navX->ahrs->GetPitch());
	SmartDashboard::PutNumber("Roll", Robot::navX->ahrs->GetRoll());
	SmartDashboard::PutNumber("X", Robot::navX->ahrs->GetRawGyroX());
	SmartDashboard::PutNumber("Y", Robot::navX->ahrs->GetRawGyroY());
	SmartDashboard::PutNumber("Z", Robot::navX->ahrs->GetRawGyroZ());
	SmartDashboard::PutNumber("POV", Robot::oi->getjoy1()->GetPOV());
}

// Make this return true when this Command no longer needs to run execute()
bool DriveRobot::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveRobot::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveRobot::Interrupted() {

}
