// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "PrepToClimb.h"

bool ready = false;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

PrepToClimb::PrepToClimb(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pullup.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void PrepToClimb::Initialize() {
	if (Robot::pullup->CheckState() == false) {
		Robot::pullup->Drop();
		Wait(1.0);
	}
}

// Called repeatedly when this Command is scheduled to run
void PrepToClimb::Execute() {
	Robot::pullup->Segment1();
	Wait(1.0);
	Robot::pullup->Segment2();
	Wait(1.0);
	Robot::pullup->Segment3();
	Wait(1.0);
	ready = true;
}

// Make this return true when this Command no longer needs to run execute()
bool PrepToClimb::IsFinished() {
    return ready;
}

// Called once after isFinished returns true
void PrepToClimb::End() {
	ready = false;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void PrepToClimb::Interrupted() {

}
