// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RotateDegrees.h"

int degrees;
int initDegrees;
int turnDegrees;
bool rightDir;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

RotateDegrees::RotateDegrees(int targetDegrees): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::navX.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis.get());
	degrees = targetDegrees;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void RotateDegrees::Initialize() {
	Robot::navX->ahrs->ZeroYaw();
	Wait(0.08);
	initDegrees = (Robot::navX->YawGet360());
	turnDegrees = initDegrees-degrees;
	if (turnDegrees > initDegrees) {
		rightDir = true;
	}

	if (turnDegrees >= 360) {
		turnDegrees = turnDegrees % 360;
	}

	if (turnDegrees <= 0) {
		turnDegrees = turnDegrees % 360 + 360;
	}
}

// Called repeatedly when this Command is scheduled to run
void RotateDegrees::Execute() {
	if (rightDir == true) {
		Robot::chassis->Drive(0.75, -0.75);
	} else if (rightDir == false) {
		Robot::chassis->Drive(-0.75, 0.75);
	} else {
		Robot::chassis->Drive(0.0, 0.0);
	}
	Wait(0.05);
}

// Make this return true when this Command no longer needs to run execute()
bool RotateDegrees::IsFinished() {
    return ((Robot::navX->YawGet360()) <= (turnDegrees + 3) && (Robot::navX->YawGet360()) >= (turnDegrees - 3));
}

// Called once after isFinished returns true
void RotateDegrees::End() {
	Robot::chassis->Drive(0.0, 0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RotateDegrees::Interrupted() {

}
