// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Joystick> joy3;
	std::shared_ptr<JoystickButton> b3_3;
	std::shared_ptr<JoystickButton> b3_2;
	std::shared_ptr<JoystickButton> b3_1;
	std::shared_ptr<Joystick> joy2;
	std::shared_ptr<JoystickButton> b2_2;
	std::shared_ptr<JoystickButton> b2_1;
	std::shared_ptr<Joystick> joy1;
	std::shared_ptr<JoystickButton> b1_1;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<JoystickButton> b3_4;
	std::shared_ptr<JoystickButton> b1_3;
	std::shared_ptr<JoystickButton> b2_3;
	std::shared_ptr<JoystickButton>	b3_5;

public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> getjoy1();
	std::shared_ptr<Joystick> getjoy2();
	std::shared_ptr<Joystick> getjoy3();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
