// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Robot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
std::shared_ptr<Chassis> Robot::chassis;
std::shared_ptr<Shooter> Robot::shooter;
std::shared_ptr<NavX> Robot::navX;
std::shared_ptr<Targeting> Robot::targeting;
std::shared_ptr<Compressor> Robot::compressor;
std::shared_ptr<Pullup> Robot::pullup;
std::unique_ptr<OI> Robot::oi;
std::shared_ptr<Transmission> Robot::transmission;
std::shared_ptr<ShooterActuator> Robot::shooterActuator;
EaglestrikeErrorLogger* Robot::logger;
std::shared_ptr<PDP> Robot::kPDP;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
std::shared_ptr<SendableChooser> chooser;

void Robot::RobotInit() {
	RobotMap::init();

	logger = new EaglestrikeErrorLogger("/home/lvuser/shooter.log");
	logger->log("Initializing logger...");
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    chassis.reset(new Chassis());
    shooter.reset(new Shooter());
    navX.reset(new NavX());
    targeting.reset(new Targeting());
    compressor.reset(new Compressor());
    pullup.reset(new Pullup());
    transmission.reset(new Transmission());
    shooterActuator.reset(new ShooterActuator());
    kPDP.reset(new PDP());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	// This MUST be here. If the OI creates Commands (which it very likely
	// will), constructing it during the construction of CommandBase (from
	// which commands extend), subsystems are not guaranteed to be
	// yet. Thus, their requires() statements may grab null pointers. Bad
	// news. Don't move it.
	oi.reset(new OI());

	// instantiate the command used for the autonomous period
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	chooser.reset (new SendableChooser);
	chooser->AddDefault("Position 4", new AutoPos4());
	chooser->AddObject("Position 3", new AutoPos3());
	chooser->AddObject("Position 1", new AutoPos1());
	chooser->AddObject("Position 2", new AutoPos2());
	chooser->AddObject("Position 5", new AutoPos5());
	SmartDashboard::PutData("Auto Modes", chooser.get());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
  }

/**
 * This function is called when the disabled button is hit.
 * You can use it to reset subsystems before shutting down.
 */
void Robot::DisabledInit(){

}

void Robot::DisabledPeriodic() {
	Scheduler::GetInstance()->Run();
}

void Robot::AutonomousInit() {
	autonomousCommand.reset((Command*) chooser->GetSelected());

	if (autonomousCommand.get() != nullptr)
		autonomousCommand->Start();
}

void Robot::AutonomousPeriodic() {
	Scheduler::GetInstance()->Run();
}

void Robot::TeleopInit() {
	// This makes sure that the autonomous stops running when
	// teleop starts running. If you want the autonomous to
	// continue until interrupted by another command, remove
	// these lines or comment it out.
	if (autonomousCommand.get() != nullptr)
		autonomousCommand->Cancel();
}

void Robot::TeleopPeriodic() {
	Scheduler::GetInstance()->Run();
}

void Robot::TestPeriodic() {
	lw->Run();
}

START_ROBOT_CLASS(Robot);

